package com.arjesh.boxboxassignment.ui.upcomingRaceDetails

import androidx.compose.foundation.Image
import androidx.compose.foundation.background
import androidx.compose.foundation.clickable
import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Box
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.offset
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.layout.size
import androidx.compose.foundation.layout.statusBarsPadding
import androidx.compose.foundation.shape.CircleShape
import androidx.compose.material3.HorizontalDivider
import androidx.compose.material3.Icon
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.runtime.collectAsState
import androidx.compose.runtime.getValue
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.clip
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.layout.ContentScale
import androidx.compose.ui.res.painterResource
import androidx.compose.ui.res.stringResource
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import com.arjesh.boxboxassignment.R
import com.arjesh.boxboxassignment.theme.DarkBG
import com.arjesh.boxboxassignment.theme.DividerColor
import com.arjesh.boxboxassignment.theme.GothamFonts
import com.arjesh.boxboxassignment.theme.ListElementPadding
import com.arjesh.boxboxassignment.theme.MonteserratFonts
import com.arjesh.boxboxassignment.theme.RootScreenPadding
import com.arjesh.boxboxassignment.theme.UpcomingCountDownTextColor
import com.arjesh.boxboxassignment.ui.navigation.Route
import com.arjesh.boxboxassignment.ui.upcomingRaceDetails.components.CountdownTimer
import org.koin.androidx.compose.koinViewModel

@Composable
fun UpcomingRaceDetailsScreen(
    onNavigate: (Route) -> Unit
) {
    val viewModel = koinViewModel<UpcomingRaceDetailsViewModel>()
    val state by viewModel.uiState.collectAsState()

    Box(
        Modifier
            .fillMaxSize()
            .background(DarkBG)
    ) {
        //This can be generated by layering brush gradients, but using image because of time constraint
        Image(
            painter = painterResource(R.drawable.bg_upcoming_race_details),
            modifier = Modifier
                .fillMaxWidth(),
            contentScale = ContentScale.Crop,
            contentDescription = null,
        )
        Column(
            modifier = Modifier
                .fillMaxSize()
                .padding(horizontal = RootScreenPadding)
                .statusBarsPadding(),
        ) {
            Box(
                modifier = Modifier
                    .fillMaxWidth()
                    .padding(vertical = RootScreenPadding)
            ) {
                Icon(
                    painter = painterResource(R.drawable.ic_back),
                    contentDescription = "back icon",
                    modifier = Modifier
                        .offset(x = (-6).dp)
                        .align(Alignment.CenterStart)
                        .clip(CircleShape)
                        .clickable(
                            onClick = {
                                onNavigate(Route.Back)
                            }
                        )
                        .padding(6.dp),
                )
                Text(
                    text = stringResource(R.string.upcoming_race),
                    fontFamily = MonteserratFonts,
                    fontSize = 16.sp,
                    fontWeight = FontWeight.SemiBold,
                    modifier = Modifier.align(Alignment.Center)
                )
            }
            Box(
                modifier = Modifier.fillMaxWidth()
            ) {
                Column(
                    modifier = Modifier
                        .padding(vertical = RootScreenPadding)
                        .align(Alignment.CenterStart),
                    verticalArrangement = Arrangement.spacedBy(4.dp)
                ) {
                    Text(
                        text = stringResource(
                            R.string.round_s,
                            state.race?.round?.toString() ?: stringResource(R.string._00)
                        ),
                        fontFamily = MonteserratFonts,
                        fontSize = 14.sp,
                        lineHeight = 14.sp,
                        fontWeight = FontWeight.SemiBold,
                        color = Color.White,
                    )
                    Text(
                        text = state.race?.raceName ?: stringResource(R.string.unknown),
                        fontFamily = MonteserratFonts,
                        fontSize = 22.sp,
                        lineHeight = 26.sp,
                        fontWeight = FontWeight.Black,
                        color = Color.White,
                    )
                    Text(
                        text = state.race?.circuitId?.replace("_", " ") ?: stringResource(R.string.unknown),
                        fontFamily = MonteserratFonts,
                        fontSize = 14.sp,
                        lineHeight = 14.sp,
                        fontWeight = FontWeight.SemiBold,
                        color = UpcomingCountDownTextColor,
                    )
                    Text(
                        text = state.race?.displayStartEndTime ?: stringResource(R.string.unknown),
                        fontFamily = MonteserratFonts,
                        fontSize = 14.sp,
                        lineHeight = 14.sp,
                        fontWeight = FontWeight.SemiBold,
                    )
                    Spacer(Modifier.height(22.dp)) //to add 30.dp space, 30+4+4.
                    Text(
                        text = stringResource(R.string.fp1_starts_in),
                        fontFamily = GothamFonts,
                        fontSize = 11.sp,
                        lineHeight = 11.sp,
                        fontWeight = FontWeight.Medium,
                    )
                    CountdownTimer(
                        targetTimeInSeconds = state.race?.raceStartTime ?: 0,
                    )
                }
                Image(
                    painter = painterResource(R.drawable.img_circuit_3d),
                    modifier = Modifier
                        .size(180.dp)
                        .align(Alignment.CenterEnd),
                    contentDescription = "3d circuit image",
                )
            }
            Spacer(Modifier.height(50.dp))
            UpcomingDetailsItem(
                title = "São Paulo Circuit",
                description = "Bahrain International circuit is located in Sakhir, Bahrain and it was designed by German architect Hermann Tilke. It was built on the site of a former camel farm, in Sakhir. It measures 5.412 km, has 15 corners and 3 DRS Zones. The Grand Prix have 57 laps. This circuit has 6 alternative layouts.",
                modifier = Modifier.fillMaxWidth(),
            )
            Spacer(Modifier.height(30.dp))
            UpcomingDetailsItem(
                title = "Circuit Facts",
                description = "His brother Arthur Leclerc is currently set to race for DAMS in the 2023 F2 Championship",
                modifier = Modifier.fillMaxWidth(),
            )
            HorizontalDivider(
                color = DividerColor,
                modifier = Modifier
                    .padding(vertical = ListElementPadding)
            )
            UpcomingDetailsItem(
                description = "He’s not related to Édouard Leclerc, the founder of a French supermarket chain",
                modifier = Modifier.fillMaxWidth(),
            )
            HorizontalDivider(
                color = DividerColor,
                modifier = Modifier
                    .padding(vertical = ListElementPadding)
            )
        }
    }
}

@Composable
fun UpcomingDetailsItem(
    title: String? = null,
    description: String,
    modifier: Modifier = Modifier,
) {
    Column(
        modifier = modifier
    ) {
        title?.let {
            Text(
                text = it,
                fontFamily = MonteserratFonts,
                fontSize = 18.sp,
                fontWeight = FontWeight.Bold,
                lineHeight = 18.sp,
            )
            Spacer(Modifier.height(ListElementPadding))
        }
        Text(
            text = description,
            fontFamily = MonteserratFonts,
            fontSize = 12.sp,
            fontWeight = FontWeight.Medium,
            lineHeight = 18.sp,
        )
    }
}
